### ISSUE TITLE
Add Candle as a supported Chain

### ISSUE THREAD

**Issue by samisbakedham** [levelkdev/swapr-dapp#1030]
**Description**
Add Candle as a supported Chain. 

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Additional resources**
Some examples of resources that might be added here
* EVM-compatible
* https://cndlchain.com
