### ISSUE TITLE
Upgrade to Webpack v5

### ISSUE THREAD

**Issue by berteotti** [levelkdev/swapr-dapp#1063]
**Description**
Create a POC for the Webpack v5 upgrade.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] POC is complete (Developer)
- [ ] Changes are tested for further development (Developer)
- [ ] New task is created if changes are approved

# Dependencies
- [x] React Router Dom V6
- [x] React v18
- [x] React Redux v8
- [x] Replace old dependencies

**Comment by wixzi** [comment]
Tried and reverted since its to much refactor for a single task since new CRA will upgrade redux, react and react-router-dom v6 and need to replace old dependencies. So will do another attempt after upgrading each library in separate issues.

**Comment by wixzi** [comment]
Upgraded to webpack 5 and cra 5
